# Run Travis CI for R via Docker
#
# Made by Dirk Eddelbuettel in August 2018 and released under GPL (>=2)

os: linux
dist: trusty
sudo: required
services: docker

env:
  global:
    - DOCKER_OPTS="--rm -ti -v $(pwd):/mnt -w /mnt"
      DOCKER_CNTR="eddelbuettel/rcpp-testing"
      R_BLD_CHK_OPTS="--no-build-vignettes --no-manual"

env:
  global:
    - RunAllRcppTests="yes"

before_install:
  - docker pull ${DOCKER_CNTR}
  - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} r -p -e 'sessionInfo()'

install:
  # Rcpp test runner can be forced to run more tests via this a variable
  - echo 'RunAllRcppTests="yes"' > ~/.Renviron
  #
  - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} R CMD build ${R_BLD_CHK_OPTS} .

script:
  - docker run ${DOCKER_OPTS} ${DOCKER_CNTR} R CMD check ${R_BLD_CHK_OPTS} Rcpp_*.tar.gz

after_success:
  - r -l covr -e 'codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: kUzgzzpgBMc6a+qSjGovfU14U7x9GUXfghDgyF5qBaND/MjFpkmTBfW438Out2buiY+hFNnZc4zThifJM300cOXbcwVentmzuVQ5lLjBhTDvwQgdqytgWr/Ds9dErBeMXr178UD3MJXSOCLhO0wUke2xp2ZsDhsjquT+vFYnuk8=
